const Discord = require("discord.js");
const bot = new Discord.Client()
const ms = require("ms")
const prefix = "#"
module.exports.run = async (bot, message) => {
if(!message.guild.member(message.author).hasPermission("MANAGE_ROLES")) return message.channel.send("**Please Check Your Permissions !**")
if(!message.guild.member(message.client.user).hasPermission("MANAGE_ROLES")) return message.channel.send("**Please Check My Permissions !**")
message.guild.roles.create({data: {name: "1",color: "#000001"}})
message.guild.roles.create({data: {name: "2",color: "#0a0a0a"}})
message.guild.roles.create({data: {name: "3",color: "#131313"}})
message.guild.roles.create({data: {name: "4",color: "#1f1f1f"}})
message.guild.roles.create({data: {name: "5",color: "#242424"}})
message.guild.roles.create({data: {name: "6",color: "#333333"}})
message.guild.roles.create({data: {name: "7",color: "#5c5c5c"}})
message.guild.roles.create({data: {name: "8",color: "#797979"}})
message.guild.roles.create({data: {name: "9",color: "#a0a0a0"}})
message.guild.roles.create({data: {name: "10",color: "#cecece"}})
message.guild.roles.create({data: {name: "11",color: "#ffffff"}})
message.guild.roles.create({data: {name: "12",color: "#110000"}})
message.guild.roles.create({data: {name: "13",color: "#2c0000"}}) 
message.guild.roles.create({data: {name: "14",color: "#380401"}})
message.guild.roles.create({data: {name: "15",color: "#4b0101"}})
message.guild.roles.create({data: {name: "16",color: "#520000"}})
message.guild.roles.create({data: {name: "17",color: "#580000"}})
message.guild.roles.create({data: {name: "18",color: "#810000"}})
message.guild.roles.create({data: {name: "19",color: "#a00000"}})
message.guild.roles.create({data: {name: "20",color: "#c90000"}})
message.guild.roles.create({data: {name: "21",color: "#f10000"}})
message.guild.roles.create({data: {name: "22",color: "#ff0000"}})
message.guild.roles.create({data: {name: "23",color: "#310d00"}})
message.guild.roles.create({data: {name: "24",color: "#471d00"}})
message.guild.roles.create({data: {name: "25",color: "#632500"}})
message.guild.roles.create({data: {name: "26",color: "#702900"}})
message.guild.roles.create({data: {name: "27",color: "#743300"}})
message.guild.roles.create({data: {name: "28",color: "#793600"}})
message.guild.roles.create({data: {name: "29",color: "#8a4600"}})
message.guild.roles.create({data: {name: "30",color: "#b34700"}})
let embed = new Discord.MessageEmbed()
.setDescription("**Done Has Have Been Created 30 Colors !**")
.setColor("RANDOM")
return message.channel.send({embed: embed})
}

module.exports.help={name:"ccolors"}